#!/bin/bash

[[ $# -gt 0 ]] || die "Not enough arguments"

die() {
	echo "$@" >&2
	exit 1
}

DIRNAME=`dirname $1`

case $1 in
	*_tb)
		FILE="test/${1}.v"
		[[ -f $FILE ]] && die "$FILE already exists"
		mkdir -p "test/$DIRNAME"
		echo -e "//TODO Testbench $1" >> $FILE
		echo -e "" >> $FILE
		echo -e '`include "defines.v"' >> $FILE
		echo -e "" >> $FILE
		echo -e "module $1;" >> $FILE
		echo -e "" >> $FILE
		echo -e "initial begin" >> $FILE
		echo -e "\t\`ifdef TRACEFILE" >> $FILE
		echo -e "\t\$dumpfile(\`TRACEFILE);" >> $FILE
		echo -e "\t\$dumpvars(0, $1);" >> $FILE
		echo -e "\t\`endif" >> $FILE
		echo -e "end" >> $FILE
		echo -e "" >> $FILE
		echo -e "endmodule" >> $FILE
		echo "Created $FILE"
		;;
	*)
		FILE="src/${1}.v"
		[[ -f $FILE ]] && die "$FILE already exists"
		mkdir -p "src/$DIRNAME"
		echo -e "\`ifndef _$1" >> $FILE
		echo -e "\`define _$1" >> $FILE
		echo -e "" >> $FILE
		echo -e '`include "defines.v"' >> $FILE
		echo -e "" >> $FILE
		echo -e "//TODO Module $1" >> $FILE
		echo -e "module $1;" >> $FILE
		echo -e "endmodule" >> $FILE
		echo -e "" >> $FILE
		echo -e "\`endif" >> $FILE
		echo "Created $FILE"
		;;
esac
