#!/bin/bash

[[ $# -gt 0 ]] || { utils/log error Fatal; exit 1; }

ps | grep -sq gtkwave && { utils/log warn GTKWave already running; exit 0; }

trace=traces/$1

if [[ ! -f $trace ]]; then
	trace=`find . -name $1`
	[[ -f $trace ]] || { utils/log error "No valid trace file"; exit 1; }
	utils/log warn "Using $trace"
fi

utils/log info "Launching GTKWave"
gtkwave -A -f $trace >/dev/null  2>&1 &
