#!/bin/bash

[[ $# -gt 0 ]] || die "Fatal"

declare -a includes=()
declare -a todo=("$1")
declare -a results=()

contains() {
	local e
	for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 0; done
	return 1
}

die() {
	utils/log error $1	
	exit 1
}

while [[ ${#todo[@]} -gt 0 ]]; do
	file=$(find . -name ${todo[0]})
	[[ -f $file ]] || die "${todo[0]} not found"
	for i in $(grep -e "^\`include" $file | sed -n 's/`include "\(.*\)"/\1/p'); do
		contains "$i" "${todo[@]}" || contains "$i" "${includes[@]}" || todo+=("$i")
	done
	includes+=("${todo[0]}")
	todo=(${todo[@]:1:$((${#todo[@]} - 1))})
done

for i in ${includes[@]}; do
	results+=("`find . -name $i`")
done

echo "${results[@]}"
